index:
    path: /
    controller: App\Controller\LandingPageController::start

createAdmin:
    path: /add-admin
    methods: POST
    controller: App\Controller\LandingPageController::createAdmin

login:
    path: /login
    controller: App\Controller\LoginController::login
