index:
    path: /
    controller: App\Controller\LandingPageController::start

createAdmin:
    path: /add-admin
    methods: POST
    controller: App\Controller\LandingPageController::createAdmin

loginPage:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::start

home:
    path: /admin/dashboard
    methods: GET
    controller: App\Controller\DashboardController::start

users:
    path: /admin/users
    methods: GET
    controller: App\Controller\UsersController::start

getMens:
    path: /users/men
    methods: GET
    controller: App\Controller\UsersController::getMens

getWomens:
    path: /users/women
    methods: GET
    controller: App\Controller\UsersController::getWomens

getAllUsers:
    path: /users/all
    methods: GET
    controller: App\Controller\UsersController::getAllUsers

getAllActiveUsers:
    path: /users/active/all
    methods: GET
    controller: App\Controller\UsersController::getAllActiveUsers

getSumUsersSub:
    path: /users/sub
    methods: GET
    controller: App\Controller\BillingController::getSumUsersSub

getByAges:
    path: /users/ages
    methods: GET
    controller: App\Controller\UsersController::getByAges

getByEmail:
    path: /users/emails
    methods: GET
    controller: App\Controller\DashboardController::getByEmail

getListUsers:
    path: /users/list
    methods: POST
    controller: App\Controller\UsersController::listUsers

getCountListUsers:
    path: /users/countlist
    methods: GET
    controller: App\Controller\UsersController::countListUsers

getId:
    path: /user/id
    methods: GET
    controller: App\Controller\UsersController::getId

deleteUser:
    path: /user/delete
    methods: post
    controller: App\Controller\UsersController::deleteUser

logout:
    path: /logout

