index:
    path: /
    controller: App\Controller\LandingPageController::start

createAdmin:
    path: /add-admin
    methods: POST
    controller: App\Controller\LandingPageController::createAdmin

loginPage:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::start

home:
    path: /admin/dashboard
    methods: GET
    controller: App\Controller\DashboardController::start

users:
    path: /admin/users
    methods: GET
    controller: App\Controller\UsersController::start

getMens:
    path: /users/men
    methods: GET
    controller: App\Controller\UsersController::getMens

getWomens:
    path: /users/women
    methods: GET
    controller: App\Controller\UsersController::getWomens

getAllUsers:
    path: /users/all
    methods: GET
    controller: App\Controller\UsersController::getAllUsers

logout:
    path: /logout

